name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.11]

    steps:
    - uses: actions/checkout@v3

    #- name: Increase swap space to avoid CI failure
    #  uses: pierotofy/set-swap-space@master
    #  with:
    #    swap-size-gb: 10

    - name: Swap space report before modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        echo

    - name: Set Swap
      shell: bash
      run: |
          export SWAP_FILE=$(swapon --show=NAME | tail -n 1)
          sudo swapoff $SWAP_FILE
          sudo rm $SWAP_FILE
          sudo fallocate -l 13G $SWAP_FILE
          sudo chmod 600 $SWAP_FILE
          sudo mkswap $SWAP_FILE
          sudo swapon $SWAP_FILE

    - name: Swap space report after modification
      shell: bash
      run: |
        echo "Memory and swap:"
        free -h
        echo
        swapon --show
        echo

    - name: pwd
      run: pwd

    - name: ls
      run: ls -l

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: which pip after python setup
      run: |
        python -m pip install --upgrade pip
        pip --version

    - name: Install python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install package
      run: pip install -v .

    - name: Run tests
      run: pytest

